"""age column added

Revision ID: dcc0489f7a2f
Revises: 
Create Date: 2025-05-27 12:13:17.493625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcc0489f7a2f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_model_id'), table_name='test_model')
    op.drop_index(op.f('ix_test_model_name'), table_name='test_model')
    op.drop_table('test_model')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_model',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_model_name'), 'test_model', ['name'], unique=False)
    op.create_index(op.f('ix_test_model_id'), 'test_model', ['id'], unique=False)
    # ### end Alembic commands ###
